// <auto-generated />
namespace ShopMate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class sale_add_field_currency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sale_add_field_currency));
        
        string IMigrationMetadata.Id
        {
            get { return "202605052316427_sale_add_field_currency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
