// <auto-generated />
namespace ShopMate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Product_add_filled_unit_sale_price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_add_filled_unit_sale_price));
        
        string IMigrationMetadata.Id
        {
            get { return "202604280805254_Product_add_filled_unit_sale_price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
