// <auto-generated />
namespace ShopMate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class product_add_field_number_of_unitCasesq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_add_field_number_of_unitCasesq));
        
        string IMigrationMetadata.Id
        {
            get { return "202605082355222_product_add_field_number_of_unitCasesq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
