// <auto-generated />
namespace ShopMate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class product_num_of_singles_in_case_not_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_num_of_singles_in_case_not_null));
        
        string IMigrationMetadata.Id
        {
            get { return "202606020852381_product_num_of_singles_in_case_not_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
