// <auto-generated />
namespace ShopMate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class product_changenumofunitstounits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_changenumofunitstounits));
        
        string IMigrationMetadata.Id
        {
            get { return "202605090032133_product_change-numof-units-to-units"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
